/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje;

import java.sql.*;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmet
 */
public class duzenleme extends javax.swing.JFrame implements Helper{
    PreparedStatement pt1;
    ResultSet rs1;
        String ad;
        String koltukno;
        String tc;
        String tarih;

    private Connect conn=new Connect();
    Connection con=conn.connDb();
    PreparedStatement pt;
    ResultSet rs;
     PreparedStatement pt3;
    ResultSet rs3;
    
    /**
     * Creates new form duzenleme
     * @param bilgiDuzen
     */
    public duzenleme(String[] bilgiDuzen) {
        this.ad = bilgiDuzen[2];
        this.koltukno = bilgiDuzen[1];
        this.tc = bilgiDuzen[3];
        this.tarih=bilgiDuzen[4];
        
        initComponents();
        seferadf.setText(bilgiDuzen[0]);
        seferadf.disable();
        koltuknof.setText(bilgiDuzen[1]);
        adf.setText(bilgiDuzen[2]);
        tcnof.setText(bilgiDuzen[3]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seferadf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        koltuknof = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tcnof = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sefer Adı");

        jLabel2.setText("Koltuk Numarası");

        jLabel3.setText("Yolcu Adı");

        jLabel4.setText("Tc No");

        jButton1.setText("Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addComponent(seferadf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(koltuknof)
                                    .addComponent(adf)
                                    .addComponent(tcnof))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seferadf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(koltuknof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(adf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tcnof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        
        
        try {
            
            Statement a=con.createStatement();
            Statement b=con.createStatement();
            pt1=con.prepareStatement("select koltuk from koltuk where koltuk='"+koltuknof.getText()+"' and tariH='"+tarih+"'");
            rs1=pt1.executeQuery();
            
            
            if(koltuknof.getText().length()==0 || adf.getText().length()==0 || tcnof.getText().length()==0){
                
                Helper.showMesage("fill");
            }
            else if(rs1.next()    && !koltuknof.getText().equals(koltukno)){
            JOptionPane.showMessageDialog(this," Bu koltuk dolu ");
            
            }
             else if(Integer.valueOf(koltuknof.getText())>28 ){
               JOptionPane.showMessageDialog(this,"Yanlış numara girdiniz");
               }
            
            else{
                try {
                    pt=con.prepareStatement("select tckimlik from koltuk where koltuk.tckimlik='"+tcnof.getText()+"' and koltuk.tariH='"+tarih+"'");
                    rs=pt.executeQuery();
                    if(rs.next()&& !tcnof.getText().equals(tc) ){
                        JOptionPane.showMessageDialog(this," Bu tarihte aynı tc ye sahip başka bir yolcu bulunmakta.Başka bir Tc deneyiniz ");
                    }
                    
                    else{
                            
                            
                            try {
                            // TODO add your handling code here:
                            
                            String degis2="update otobus set durum='bos' where koltuk='"+koltukno+"' and tarih='"+ tarih+"'" ;
                            String degis="update otobus set durum='dolu' where koltuk='"+koltuknof.getText()+"' and tarih='"+ tarih+"'" ;
                            b.execute(degis2);
                            a.execute(degis);
                            String guncelleme="update koltuk set koltuk.koltuk='"+koltuknof.getText()+"',koltuk.musteriad='"+adf.getText()+"',koltuk.tckimlik='"+tcnof.getText()+"' where koltuk.koltuk='"+koltukno+"' and koltuk.musteriad='"+ad+"' and tckimlik='"+tc+"'";
                            Statement sta=con.createStatement();
                            sta.execute(guncelleme);
                            
                            
                            JOptionPane.showMessageDialog(this," Kullanıcı Güncellendi ");
                            this.setVisible(false);
                            
                            
                            } catch (SQLException ex) {
                            Logger.getLogger(duzenleme.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                            }
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(duzenleme.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(duzenleme.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(duzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(duzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(duzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(duzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField koltuknof;
    private javax.swing.JTextField seferadf;
    private javax.swing.JTextField tcnof;
    // End of variables declaration//GEN-END:variables
}
