/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje;

import java.awt.Color;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JButton;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
 


/**
 *
 * @author ahmet
 */
public class yolcuEklePage extends javax.swing.JFrame implements Helper {
    Border border = new LineBorder(Color.WHITE, 4, true);
    Border border1 = new LineBorder(Color.RED, 4, true);
    private Connect conn=new Connect();
    Connection con=conn.connDb();
     String otoad;
    PreparedStatement st;
    PreparedStatement st1;

   

    
    
    
    
    /**
     * Creates new form yolcuEklePage
     */
    public yolcuEklePage() {
        initComponents();
           adtext.setVisible(false);
            tctext.setVisible(false);
            koltext.setVisible(false);
            tartext.setVisible(false);
            adsoyadField.setVisible(false);
            kimlikfield.setVisible(false);
            koltuknoField.setVisible(false);
            tarihfield.setVisible(false);
            eklemeBTT.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        adtext = new javax.swing.JLabel();
        adsoyadField = new javax.swing.JTextField();
        koltext = new javax.swing.JLabel();
        tctext = new javax.swing.JLabel();
        kimlikfield = new javax.swing.JTextField();
        koltuknoField = new javax.swing.JTextField();
        eklemeBTT = new javax.swing.JButton();
        göstermedate = new javax.swing.JButton();
        tartext = new javax.swing.JLabel();
        tarihfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        birbt = new javax.swing.JButton();
        ikibt = new javax.swing.JButton();
        ucbt = new javax.swing.JButton();
        dortbt = new javax.swing.JButton();
        besbt = new javax.swing.JButton();
        altibt = new javax.swing.JButton();
        yedibt = new javax.swing.JButton();
        sekizbt = new javax.swing.JButton();
        dokuzbt = new javax.swing.JButton();
        onbt = new javax.swing.JButton();
        onbirbt = new javax.swing.JButton();
        onikibt = new javax.swing.JButton();
        onucbt = new javax.swing.JButton();
        ondortbt = new javax.swing.JButton();
        onbesbt = new javax.swing.JButton();
        onaltibt = new javax.swing.JButton();
        onyedibt = new javax.swing.JButton();
        onsekizbt = new javax.swing.JButton();
        ondokuzbt = new javax.swing.JButton();
        yirmibt = new javax.swing.JButton();
        yirmibirbt = new javax.swing.JButton();
        yirmiikibt = new javax.swing.JButton();
        yirmiucbt = new javax.swing.JButton();
        yirmidortbt = new javax.swing.JButton();
        yirmibesbt = new javax.swing.JButton();
        yirmialtibt = new javax.swing.JButton();
        yirmiyedibt = new javax.swing.JButton();
        yirmisekizbt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tarih seçiniz");

        adtext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adtext.setText("Ad Soyad");

        koltext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        koltext.setText("Koltuk Numarası");

        tctext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tctext.setText("TC kimlik");

        eklemeBTT.setText("Ekle");
        eklemeBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklemeBTTActionPerformed(evt);
            }
        });

        göstermedate.setText("Ara");
        göstermedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                göstermedateActionPerformed(evt);
            }
        });

        tartext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tartext.setText("Tarih");

        tarihfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tctext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(koltext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tartext)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(göstermedate))
                        .addComponent(adsoyadField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kimlikfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(koltuknoField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eklemeBTT, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(tarihfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(482, 482, 482))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(göstermedate, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adtext)
                    .addComponent(adsoyadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctext)
                    .addComponent(kimlikfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(koltext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(tartext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(eklemeBTT)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(koltuknoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarihfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        birbt.setText("1");
        birbt.setBorder(border);
        birbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birbtActionPerformed(evt);
            }
        });

        ikibt.setText("2");
        ikibt.setBorder(border);
        ikibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikibtActionPerformed(evt);
            }
        });

        ucbt.setText("3");
        ucbt.setBorder(border);
        ucbt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ucbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucbtActionPerformed(evt);
            }
        });

        dortbt.setText("4");
        dortbt.setBorder(border);
        dortbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dortbtActionPerformed(evt);
            }
        });

        besbt.setText("5");
        besbt.setBorder(border);
        besbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besbtActionPerformed(evt);
            }
        });

        altibt.setText("6");
        altibt.setBorder(border);
        altibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altibtActionPerformed(evt);
            }
        });

        yedibt.setText("7");
        yedibt.setBorder(border);
        yedibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yedibtActionPerformed(evt);
            }
        });

        sekizbt.setText("8");
        sekizbt.setBorder(border);
        sekizbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sekizbtActionPerformed(evt);
            }
        });

        dokuzbt.setText("9");
        dokuzbt.setBorder(border);
        dokuzbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokuzbtActionPerformed(evt);
            }
        });

        onbt.setText("10");
        onbt.setBorder(border);
        onbt.setMaximumSize(new java.awt.Dimension(23, 23));
        onbt.setMinimumSize(new java.awt.Dimension(23, 23));
        onbt.setPreferredSize(new java.awt.Dimension(23, 23));
        onbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onbtActionPerformed(evt);
            }
        });

        onbirbt.setText("11");
        onbirbt.setBorder(border);
        onbirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onbirbtActionPerformed(evt);
            }
        });

        onikibt.setText("12");
        onikibt.setBorder(border);
        onikibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onikibtActionPerformed(evt);
            }
        });

        onucbt.setText("13");
        onucbt.setBorder(border);
        onucbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onucbtActionPerformed(evt);
            }
        });

        ondortbt.setText("14");
        ondortbt.setBorder(border);
        ondortbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ondortbtActionPerformed(evt);
            }
        });

        onbesbt.setText("15");
        onbesbt.setBorder(border);
        onbesbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onbesbtActionPerformed(evt);
            }
        });

        onaltibt.setText("16");
        onaltibt.setBorder(border);
        onaltibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaltibtActionPerformed(evt);
            }
        });

        onyedibt.setText("17");
        onyedibt.setBorder(border);
        onyedibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onyedibtActionPerformed(evt);
            }
        });

        onsekizbt.setText("18");
        onsekizbt.setBorder(border);
        onsekizbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onsekizbtActionPerformed(evt);
            }
        });

        ondokuzbt.setText("19");
        ondokuzbt.setBorder(border);
        ondokuzbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ondokuzbtActionPerformed(evt);
            }
        });

        yirmibt.setText("20");
        yirmibt.setBorder(border);
        yirmibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmibtActionPerformed(evt);
            }
        });

        yirmibirbt.setText("21");
        yirmibirbt.setBorder(border);
        yirmibirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmibirbtActionPerformed(evt);
            }
        });

        yirmiikibt.setText("22");
        yirmiikibt.setBorder(border);
        yirmiikibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmiikibtActionPerformed(evt);
            }
        });

        yirmiucbt.setText("23");
        yirmiucbt.setBorder(border);
        yirmiucbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmiucbtActionPerformed(evt);
            }
        });

        yirmidortbt.setText("24");
        yirmidortbt.setBorder(border);
        yirmidortbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmidortbtActionPerformed(evt);
            }
        });

        yirmibesbt.setText("25");
        yirmibesbt.setBorder(border);
        yirmibesbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmibesbtActionPerformed(evt);
            }
        });

        yirmialtibt.setText("26");
        yirmialtibt.setBorder(border);
        yirmialtibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmialtibtActionPerformed(evt);
            }
        });

        yirmiyedibt.setText("27");
        yirmiyedibt.setBorder(border);
        yirmiyedibt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmiyedibtActionPerformed(evt);
            }
        });

        yirmisekizbt.setText("28");
        yirmisekizbt.setBorder(border);
        yirmisekizbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirmisekizbtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Şöför");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Kapı");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ikibt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ucbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yirmisekizbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altibt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(besbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dortbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(yirmiyedibt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(yirmialtibt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yedibt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekizbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokuzbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(onbirbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(onikibt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(onbesbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ondortbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(onucbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(onyedibt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onsekizbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onaltibt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ondokuzbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yirmibt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yirmibirbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(yirmibesbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yirmidortbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yirmiucbt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yirmiikibt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(271, 271, 271))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dortbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yedibt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onucbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onaltibt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ondokuzbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ikibt)
                    .addComponent(besbt)
                    .addComponent(sekizbt)
                    .addComponent(onbirbt)
                    .addComponent(ondortbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onyedibt)
                    .addComponent(yirmibt)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ucbt)
                    .addComponent(altibt)
                    .addComponent(dokuzbt)
                    .addComponent(onikibt)
                    .addComponent(onbesbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onsekizbt)
                    .addComponent(yirmibirbt))
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yirmiikibt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yirmiucbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yirmidortbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yirmibesbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yirmialtibt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yirmiyedibt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yirmisekizbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ucbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucbtActionPerformed
        koltuknoField.setText("3");


    }//GEN-LAST:event_ucbtActionPerformed

    private void birbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birbtActionPerformed
        koltuknoField.setText("1");
    }//GEN-LAST:event_birbtActionPerformed

    private void ikibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("2");
    }//GEN-LAST:event_ikibtActionPerformed

    private void besbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("5");
    }//GEN-LAST:event_besbtActionPerformed

    private void yirmisekizbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmisekizbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("28");
    }//GEN-LAST:event_yirmisekizbtActionPerformed

    private void onikibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onikibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("12");
    }//GEN-LAST:event_onikibtActionPerformed

    private void dortbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dortbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("4");
    }//GEN-LAST:event_dortbtActionPerformed

    private void altibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("6");
    }//GEN-LAST:event_altibtActionPerformed

    private void yedibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yedibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("7");
    }//GEN-LAST:event_yedibtActionPerformed

    private void sekizbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sekizbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("8");
    }//GEN-LAST:event_sekizbtActionPerformed

    private void dokuzbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokuzbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("9");
    }//GEN-LAST:event_dokuzbtActionPerformed

    private void onbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("10");
    }//GEN-LAST:event_onbtActionPerformed

    private void onbirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onbirbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("11");
    }//GEN-LAST:event_onbirbtActionPerformed

    private void onucbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onucbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("13");
    }//GEN-LAST:event_onucbtActionPerformed

    private void ondortbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ondortbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("14");
    }//GEN-LAST:event_ondortbtActionPerformed

    private void onbesbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onbesbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("15");
    }//GEN-LAST:event_onbesbtActionPerformed

    private void onaltibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaltibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("16");
    }//GEN-LAST:event_onaltibtActionPerformed

    private void onyedibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onyedibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("17");
    }//GEN-LAST:event_onyedibtActionPerformed

    private void onsekizbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onsekizbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("18");
    }//GEN-LAST:event_onsekizbtActionPerformed

    private void ondokuzbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ondokuzbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("19");
    }//GEN-LAST:event_ondokuzbtActionPerformed

    private void yirmibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("20");
    }//GEN-LAST:event_yirmibtActionPerformed

    private void yirmibirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmibirbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("21");
    }//GEN-LAST:event_yirmibirbtActionPerformed

    private void yirmiikibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmiikibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("22");
    }//GEN-LAST:event_yirmiikibtActionPerformed

    private void yirmiucbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmiucbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("23");
    }//GEN-LAST:event_yirmiucbtActionPerformed

    private void yirmidortbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmidortbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("24");
    }//GEN-LAST:event_yirmidortbtActionPerformed

    private void yirmibesbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmibesbtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("25");
    }//GEN-LAST:event_yirmibesbtActionPerformed

    private void yirmialtibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmialtibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("26");
    }//GEN-LAST:event_yirmialtibtActionPerformed

    private void yirmiyedibtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirmiyedibtActionPerformed
        // TODO add your handling code here:
         koltuknoField.setText("27");
    }//GEN-LAST:event_yirmiyedibtActionPerformed

    private void eklemeBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklemeBTTActionPerformed
               // TODO add your handling code here:
                
               
        
        
        
        
        
        
        
        
               
               if(adsoyadField.getText().length()==0 ||kimlikfield.getText().length()==0 || koltuknoField.getText().length()==0 ||tarihfield.getText().length()==0){
               
                Helper.showMesage("fill");
               
               }
               else if(Integer.valueOf(koltuknoField.getText())>28 ){
               JOptionPane.showMessageDialog(this,"Girdiğiniz Numara bulunamadı");
               }
               else{    
                   String isim=adsoyadField.getText();
                String tc=kimlikfield.getText();
                String kolno=koltuknoField.getText();
                String tar=tarihfield.getText();
        
        int i=0;
           List<JButton> copylist=new ArrayList<JButton>();
            liste(copylist);
            for(JButton a: copylist){
                   a.setEnabled(true);
                    
                   a.setBorder(border);
            }
            
        try {
            
            
            Statement std14= con.createStatement();
            ResultSet rs7=std14.executeQuery("Select tckimlik From koltuk where tckimlik='"+tc+"' and tariH='"+tar+"'");
            if(rs7.next() ){   
             JOptionPane.showMessageDialog(this,"Bu Kimliğe ait bir yolcu zaten bulunmakta");
              Statement st12= con.createStatement();
            ResultSet rs12=st12.executeQuery("Select koltuk From otobus where tarih='"+tar+"' and durum= 'dolu'");
            while(rs12.next()){
             for(JButton a: copylist){
                  if(rs12.getString(1).equals(a.getText())){
                     
                      a.setBorder(border1);
                      a.setOpaque(true);
                      a.setEnabled(false);
                   
                  }
                 
            }
            }
            }else{
                
                
                
            //Statement std= con.createStatement();
            //ResultSet rs=std.executeQuery("Select * From otobus where durum= 'dolu' and koltuk='"+kolno+"'");
            Statement std1= con.createStatement();
            ResultSet rs2=std1.executeQuery("Select musteriad,tckimlik From koltuk where koltuk='"+kolno+"' and tariH='"+tar+"'");
            
            
            
                if(rs2.next()){
                JOptionPane.showMessageDialog(this,"Bu bilet "+rs2.getString(1)+"("+rs2.getString(2)+")"+" Tarafından alınmıştır");
                
                }
               
                
            
             else {
                
                tar=tarihfield.getText();
                
             
            st=con.prepareStatement("insert into koltuk(otobusad,tariH,musteriad,tckimlik,koltuk)values(?,?,?,?,?)");
            st.setString(1,otoad);
             st.setString(2,tar);
             st.setString(3,isim);
            st.setString(4,tc);
            st.setString(5,kolno);
            st.executeUpdate();
                st1=con.prepareStatement("update otobus set durum=? where koltuk=? and tarih='"+tar+"'");
                st1.setString(1, "dolu");
                st1.setString(2, kolno);
                st1.executeUpdate();
                 JOptionPane.showMessageDialog(this,"Bilet Alındı");
             
            }   
        
        
            
          Statement st12= con.createStatement();
            ResultSet rs12=st12.executeQuery("Select koltuk From otobus where tarih='"+tar+"' and durum= 'dolu'");
            while(rs12.next()){
             for(JButton a: copylist){
                  if(rs12.getString(1).equals(a.getText())){
                      
                       a.setBorder(border1);
                      a.setOpaque(true);
                      a.setEnabled(false);
                   
                  }
                 
            }
            }
            
           
           
            }} catch (SQLException ex) {
            Logger.getLogger(yolcuEklePage.class.getName()).log(Level.SEVERE, null, ex);
        }
               }
        
        
        
    }//GEN-LAST:event_eklemeBTTActionPerformed

    private void göstermedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_göstermedateActionPerformed
        try {
            // TODO add your handling code here:
         
            int i = 0;
            SimpleDateFormat dc=new SimpleDateFormat("yyyy-MM-dd");
            String date=dc.format(jDateChooser1.getDate());
            List<JButton> copylist=new ArrayList<JButton>();
            liste(copylist);
           
            for(JButton a: copylist){
                  a.setEnabled(true);
                    
                  a.setBorder(border);
            }
            Statement std2= con.createStatement();
            ResultSet rs3=std2.executeQuery("Select * From otobus where tarih='"+date+"'");
         if(rs3.next()){ 
            adtext.setVisible(true);
            tctext.setVisible(true);
            koltext.setVisible(true);
            tartext.setVisible(true);
            adsoyadField.setVisible(true);
            kimlikfield.setVisible(true);
            koltuknoField.setVisible(true);
            tarihfield.setVisible(true);
            eklemeBTT.setVisible(true);
             
             
             
             tarihfield.setText(date);
            Statement st12= con.createStatement();
            ResultSet rs12=st12.executeQuery("Select koltuk From otobus where tarih='"+date+"' and durum= 'dolu'");
            while(rs12.next()){
             for(JButton a: copylist){
                  if(rs12.getString(1).equals(a.getText())){
                      System.out.println("1");
                      a.setBorder(border1);
                      a.setOpaque(true);
                      a.setEnabled(false);
                   
                  }
                 
            }
            }
            
            Connection con=conn.connDb();
            Statement st= con.createStatement();
            ResultSet rs=st.executeQuery("Select * From otobus where tarih='"+date+"'");
            while(rs.next()){
                 otoad=rs.getString("otobusad");
 }
            }else{
            adtext.setVisible(false);
            tctext.setVisible(false);
            koltext.setVisible(false);
            tartext.setVisible(false);
            adsoyadField.setVisible(false);
            kimlikfield.setVisible(false);
            koltuknoField.setVisible(false);
            tarihfield.setVisible(false);
            eklemeBTT.setVisible(false);
         JOptionPane.showMessageDialog(this,"Bu Tarihde Sefer Bulunamadı ");
            
         } 
        } catch (SQLException ex) {
            Logger.getLogger(yolcuEklePage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_göstermedateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminGUI a= new AdminGUI();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tarihfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihfieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yolcuEklePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yolcuEklePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yolcuEklePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yolcuEklePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yolcuEklePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adsoyadField;
    private javax.swing.JLabel adtext;
    private javax.swing.JButton altibt;
    private javax.swing.JButton besbt;
    private javax.swing.JButton birbt;
    private javax.swing.JButton dokuzbt;
    private javax.swing.JButton dortbt;
    private javax.swing.JButton eklemeBTT;
    private javax.swing.JButton göstermedate;
    private javax.swing.JButton ikibt;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kimlikfield;
    private javax.swing.JLabel koltext;
    private javax.swing.JTextField koltuknoField;
    private javax.swing.JButton onaltibt;
    private javax.swing.JButton onbesbt;
    private javax.swing.JButton onbirbt;
    private javax.swing.JButton onbt;
    private javax.swing.JButton ondokuzbt;
    private javax.swing.JButton ondortbt;
    private javax.swing.JButton onikibt;
    private javax.swing.JButton onsekizbt;
    private javax.swing.JButton onucbt;
    private javax.swing.JButton onyedibt;
    private javax.swing.JButton sekizbt;
    private javax.swing.JTextField tarihfield;
    private javax.swing.JLabel tartext;
    private javax.swing.JLabel tctext;
    private javax.swing.JButton ucbt;
    private javax.swing.JButton yedibt;
    private javax.swing.JButton yirmialtibt;
    private javax.swing.JButton yirmibesbt;
    private javax.swing.JButton yirmibirbt;
    private javax.swing.JButton yirmibt;
    private javax.swing.JButton yirmidortbt;
    private javax.swing.JButton yirmiikibt;
    private javax.swing.JButton yirmisekizbt;
    private javax.swing.JButton yirmiucbt;
    private javax.swing.JButton yirmiyedibt;
    // End of variables declaration//GEN-END:variables

   
    void liste(List<JButton> list){
       
list.add(birbt);
list.add(ikibt);
list.add(ucbt);
list.add(dortbt);
list.add(besbt);
list.add(altibt);
list.add(yedibt);
list.add(sekizbt);
list.add(dokuzbt);
list.add(onbt);
list.add(onbirbt);
list.add(onikibt);
list.add(onucbt);
list.add(ondortbt);
list.add(onbesbt);
list.add(onaltibt);
list.add(onyedibt);
list.add(onsekizbt);
list.add(ondokuzbt);
list.add(yirmibt);
list.add(yirmibirbt);
list.add(yirmiikibt);
list.add(yirmiucbt);
list.add(yirmidortbt);
list.add(yirmibesbt);
list.add(yirmialtibt);
list.add(yirmiyedibt);
list.add(yirmisekizbt);
     
    }
}

